### ISSUE TITLE
1.20.1 Zombie Pigmen affected by mod

### ISSUE THREAD

**Issue by fadingcosmos** [n643064/Apocalypse#15]
verison: 1.1.1 1.20.1-1.20.2

I've noticed that enabling this mod, it makes zombie pigmen auto aggro and attack you on sight while also gaining the effects of zombies via the config, as I seen they where moving as fast as I've setup zombies to move.

disabling the mod and exiting/entering the nether cause zombie pigmen to go back to their usual behavior.

**Comment by n643064** [comment]
https://github.com/n643064/Apocalypse/wiki/Configuration
