### ISSUE TITLE
Zombies climbing

### ISSUE THREAD

**Issue by Vipexxxx-cmd** [n643064/Apocalypse#16]
I have noticed that if i stack up the Zombies wont try to stack on top of each other, they will try to break the blocks below me but when they do that they cant stack ontop of each other anymore i hope that you can make that a feature

I am using version 1.1.1 for 1.20.1

**Comment by n643064** [comment]
The climbing mechanic is passive; if you want them to climb instead of breaking blocks then disable the block breaking goal.
