### ISSUE TITLE
No hordes spawning 1.20.1

### ISSUE THREAD

**Issue by makumaku1974** [n643064/Apocalypse#4]
Im currently testing a my own modpack and somehow when i see a message "a horde has spawned".

Nothing has spawned. kindly please check it.

**Comment by n643064** [comment]
The default config makes zombies spawn between 4 and 8 chunks away from the player, are you sure they aren't just spawning outside your visibility range?

**Comment by makumaku1974** [comment]
i am sure. But i dont know what is overwriting your mod too.

**Comment by n643064** [comment]
Please try without any other mods and with a lowered spawning distance

**Comment by BowBoy1** [comment]
is horde persistence off?
