### ISSUE TITLE
Zombies don't seem to vlimb on top of each other

### ISSUE THREAD

**Issue by VeggeieDude** [n643064/Apocalypse#5]
Heya! I was testing this mod out and zombies ever seem to climb to get to get me. I have the option enabled in the configs

**Comment by n643064** [comment]
Hi, zombies should only climb when colliding with each other, try spawning a lot of them in an enclosed space and see if it works.

**Comment by VeggeieDude** [comment]
Hm I haven't gotten it to work yet lol. But another bigger issue just came up for me. This mod makes zombie piglins naturally and permanently aggro'd

**Comment by VeggeieDude** [comment]
Ok thank you!

**Comment by kil0byt3** [comment]
Thank you for adding the toggle. It should, ideally be set to false - it makes the nether almost unplayable by default. Thank you for any consideration!
